version: '3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/projects
    tty: true
    environment:
      TZ: Asia/Tokyo
    links:
      - mongo
    command: flask run --host 0.0.0.0  --port 5000 --reload

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "20717:20717"